sudo: required

services: docker

env:
  - DOCKER_USERNAME = kazu1209
  - DOCKER_ACCESS_TOKEN = 096f96af-765f-4603-8c62-b9be5015ed18

befoer_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

