sudo: required

services: docker

#env:
#  parameter-store:
#    DOCKER_USERNAME = kazu1209
#    DOCKER_ACCESS_TOKEN = c964e35f-56ad-4bcd-a715-187ee6cb0ed3

befoer_install:
#  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin


  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test
